semi: true
singleQuote: false
printWidth: 80
useTabs: false
proseWrap: "preserve"
bracketSpacing: true
endOfLine: "crlf"
tabWidth: 2
trailingComma: "none"
svelteSortOrder: "options-scripts-markup-styles"
svelteStrictMode: true
svelteAllowShorthand: false
svelteIndentScriptAndStyle: true
overrides:
  - files: ["*.svelte"]
    parser: "prettier-plugin-svelte"
